### ISSUE TITLE
Add Task Cancellation/Update leads to My Caregivees page

### ISSUE THREAD

**Issue by juihanamshet** [cassandrale179/ci491_project#148] opened 2021-02-27 17:47 UTC
When I click on Update or Cancel Task in the Add Task page, it leads me to the My Caregivees page instead of the Tasks page. Not sure if this was intentional though.

**Comment by cassandrale179** [comment] 2021-02-27 18:06
This is intentional because right now all the Back button redirect to the Home page (Dashboard.class) since we can't move from activity to fragment yet, just activity to activity. I will close this issue since it is a duplicate of https://github.com/cassandrale179/ci491_project/issues/75

**Closed** 2021-02-27 18:06 UTC
Labels: done
